title: Griffen's Blob 
author: Griffen Livermore
email: griffen-livermore@utulsa.edu
description: > # this means to ignore newlines until "baseurl:"
  This site is dedicated ot those who question the norm... escape the reality of CIS. 

# social links
twitter_username: @heyitsgriffen
github_username:  griffenlive

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
